---

- name: Upgrade Amazon AMI Linux Kernels
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - kernel
  become: yes
  tags:
    - amazon
  # notify:
  #   - "reboot host"
