---

- name: Upgrade CentOS 7 Linux Kernels
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - kernel
    - kernel-abi-whitelists
    - kernel-debug
    - kernel-debug-devel
    - kernel-devel
    - kernel-doc
    - kernel-headers
    - kernel-tools
    - kernel-tools-libs
    - kernel-tools-libs-devel
    - perf
    - python-perf
  become: yes
  tags:
    - centos
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  # notify:
  #   - "reboot host"

- name: Upgrade CentOS 6 Linux Kernels
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - kernel
    - kernel-abi-whitelists
    - kernel-debug
    - kernel-debug-devel
    - kernel-devel
    - kernel-doc
    - kernel-headers
    - microcode_ctl
    - perf
    - python-perf
  become: yes
  tags:
    - centos
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  # notify:
  #   - "reboot host"
